100=ContentProvider.__init__()
101=ContentProvider: %s Chargement termin\u00e9

110=ContentProvider.registerInstance()
111=ContentProvider: enregistre l'instance d'un ParameterizedContentProvider avec l'argument: %s


200=ParameterizedProvider.__init__()
201=ParameterizedProvider%s Chargement termin\u00e9

210=ParameterizedProvider.createContentIdentifier()
211=Identifier: %s -> %s

220=ParameterizedProvider.queryContent()
221=Identitifer: %s ... Termin\u00e9
222=IllegalIdentifierException: %s
223=Exception python inattendue avec le traceback: %s

230=ParameterizedProvider.compareContentIds()
231=Identifiers: %s - %s ... semble \u00eatre le m\u00eame
232=Identifiers: %s - %s ... ne semble pas \u00eatre le m\u00eame


300=DataSource.__init__()
301=DataSource: Chargement termin\u00e9

310=DataSource._getUser()
311=Erreur: Impossible de charger de contenu avec un Identifier invalide: %s
312=Erreur: Impossible de r\u00e9cup\u00e9rer l'utilisateur à partir de l'Identifier: %s

320=DataSource._getUserName()
321=Erreur: Impossible de charger de contenu sans Utilisateur: %s

330=DataSource.queryClosing()
331=La base de donn\u00e9e: %s a \u00e9t\u00e9 ferm\u00e9e


400=ContentUser.__init__()
401=Le Service: %s n'est pas disponible... Veuillez installer l'extension: OAuth2OOo!!!
402=Impossible de retrouver l'utilisateur: %s chez le fournisseur: le r\u00e9seau est hors ligne!!!
403=L'utilisateur: %s est inconnu chez ce fournisseur
404=Impossible d'inserer l'utilisateur: %s dans la base de donn\u00e9es
405=ContentUser chargement termin\u00e9

410=ContentUser._getFolderContent()
411=Le contenu du dossier: %s est obtenu avec Request!!!

420=ContentUser.getDocumentContent()
421=Erreur: %s - %s


500=Content.__init__()
501=Content chargement termin\u00e9

510=Content._getMetaData()
511=Erreur: Impossible de charger le contenu avec un Identifier incomplet: %s
512=Erreur: Impossible de r\u00e9cup\u00e9rer les m\u00e9tadonn\u00e9es pour l'ID: %s et l'Uri: %s

