100=dbqueries.py -> getSqlQuery()
101=ERREUR: La requ\u00eate: '%s' est introuvable !!!

110=dbtools -> checkDataBase()
111=ERREUR de base de donn\u00e9es
112=Le pilote Hsqldb: %s n'est pas de la bonne version!!!\nLe pilote Hsqldb n\u00e9cessite la version: %s - la version charg\u00e9e: %s

200=wizard.py -> initialize()
201=Les arguments ne sont pas une s\u00e9quence ou sa longueur n'est pas deux
202=PageIds n'est pas une s\u00e9quence ou sa longueur est trop courte (ie: moins de deux)
203=Controller n'a pas les bonnes interfaces (ie: com.sun.star.ui.dialogs.XWizardController)
210=wizard.py -> enablePage()
211=La page ne peut pas \u00eatre d\u00e9sactiv\u00e9e car elle est actuellement active
212=Il n'y a pas de page avec l'ID donn\u00e9 dans le chemin courant
220=wizard.py -> enablePage()
221=Il n'y a pas de chemin avec l'indexe donn\u00e9
222=Le chemin ne peut pas \u00eatre activ\u00e9 dans l'\u00e9tat actuel de l'assistant

300=contentprovider.py -> __init__()
301=ContentProvider: %s Chargement termin\u00e9
310=contentprovider.py -> registerInstance()
311=Scheme/Plugin: %s/%s ... D\u00e9marr\u00e9
312=Scheme/Plugin: %s/%s ... Termin\u00e9
320=contentprovider.py -> _getUser()
321=Impossible d'obtenir une URI \u00e0 partir d'une URL non valide: %s
322=Impossible de r\u00e9cup\u00e9rer l'URI \u00e0 partir d'une URL incompl\u00e8te: %s
323=Impossible de r\u00e9cup\u00e9rer le nom d'utilisateur de l'URL: %s
330=contentprovider.py -> createContentIdentifier()
331=Identifier: %s ... Termin\u00e9
340=contentprovider.py -> queryContent()
341=Identitifer: %s ... ne peut \u00eatre trouv\u00e9: %s
342=Identitifer: %s ... Termin\u00e9
350=contentprovider.py -> compareContentIds()
351=Identifiers: %s - %s ... semble \u00eatre le m\u00eame
352=Identifiers: %s - %s ... ne semble pas \u00eatre le m\u00eame
360=contentprovider.py -> deregisterInstance()
361=Scheme: %s ... Termin\u00e9
370=contentprovider.py -> __del__()
371=%s d\u00e9chargement ... Termin\u00e9

400=user.py -> __init__()
401=User chargement termin\u00e9

500=identifier.py -> __init__()
501=Identifier chargement termin\u00e9
510=identifier.py -> getDocumentContent()
511=ERREUR: %s - %s

600=datasource.py -> _initializeUser()
601=Le Service: %s n'est pas disponible... Controllez vos extentions install\u00e9es!!!
602=Impossible d'inserer l'utilisateur: %s dans la base de donn\u00e9es
603=L'utilisateur: %s est inconnu chez ce fournisseur
604=Impossible de retrouver l'utilisateur: %s chez le fournisseur: le r\u00e9seau est hors ligne!!!

700=replicator.py -> _synchronize()
701=La synchronisation n'est pas possible le r\u00e9seau est hors ligne!!!
710=replicator.py -> _syncData()
711=D\u00e9marrage de la synchronisation pour l'utilisateur: %s \u00e0: %s
712=Fin de la synchronisation pour l'utilisateur: %s \u00e0 %s
720=replicator.py -> _initUser()
721=Importation des Fichiers/R\u00e9pertoires par %s requ\u00eates contenant %s \u00e9l\u00e9ments produisant %s insertion/mise \u00e0 jour
722=%s Fichiers/R\u00e9pertoires orphelin n'ont pas pu \u00eatre import\u00e9!!! Voir les details suivants...
723=Le Fichier/R\u00e9pertoire: %s, avec l'ID: %s, semble orphelin, ses parents: %s n'ont pas pu \u00eatre identifi\u00e9!
730=replicator.py -> _pushItem
731=A repliqu\u00e9 la cr\u00e9ation du dossier: %s du %s
732=A repliqu\u00e9 la cr\u00e9ation du fichier: %s du %s
733=A repliqu\u00e9 la mise \u00e0 jour du titre du fichier/r\u00e9p\u00e9rtoire: %s du %s
734=A repliqu\u00e9 la mise \u00e0 jour du fichier: '%s' du %s d'une taille de: %s
735=A repliqu\u00e9 la mise \u00e0 jour de l'effacement du fichier/r\u00e9p\u00e9rtoire: %s du %s
736=A rencontr\u00e9 une erreur lors de la r\u00e9pliquation du fichier/r\u00e9p\u00e9rtoire: %s du %s portant l'Id: %s
